name: Supervision

on:
  workflow_dispatch:
  schedule:
    - cron:  '0/10 * * * *'    # At every 10 minutes

jobs:
  cucumber_supervision_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: refs/heads/add_cucumber_based_supervision # TODO remove after PR merge

      - name: Compile with Maven
        run: mvn --batch-mode compile

      - name: Patch Cucumber properties
        env:
          DEMO_BEARER: ${{ secrets.DEMO_BEARER }}
        run: |
          sed -i -e "s/bearer=.*/bearer=$DEMO_BEARER/" ./src/test/resources/demo_env.properties
          cat ./src/test/resources/demo_env.properties

      - name: Cucumber tests with Maven on demo platform
        id: demo_supervision
        run: mvn --batch-mode test -Dcucumber.filter.tags=@tagSupervision -Dusing_platform=demo
        continue-on-error: true      

      #- name: Failure action Slack Notification
      #  if: steps.demo_supervision.outcome == 'failure'
      #  uses: rtCamp/action-slack-notify@v2.2.0
      #  env:
      #    SLACK_WEBHOOK: ${{ secrets.SUPERVISION_CHANNEL_SLACK_WEBHOOK }}
      #    SLACK_MESSAGE: 'Cucumber Supervision Failure on demo platform (https://demo.gridsuite.org/gridexplore) :bell:'

      - name: Failure action Teams notification
        if: steps.demo_supervision.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.NOTIF_MAIL_ADDRESS}}
          #ignore_cert: true
          from: ${{secrets.NOTIF_MAIL_SENDER}}
          to: ${{secrets.NOTIF_MAIL_RECIPIENTS}}
          reply_to: no-reply@rte-france.com
          subject: Integration tests fails on Demo platform
          body: 'Cucumber Supervision Failure on demo platform (<https://demo.gridsuite.org/gridexplore>) 🔔'
          convert_markdown: true
          priority: high

      - name: Failure exit
        if: steps.demo_supervision.outcome == 'failure'
        run: exit 1  # to mark the job as failed and red
        
