name: Supervision

on:
  schedule:
    - cron:  '*/5 * * * *'    # At every 5 minute


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: refs/heads/add_cucumber_based_supervision

      - name: Compile with Maven, with no test
        run: mvn --batch-mode compile
        
      - name: Patch Cucumber properties
        env:
          DEMO_BEARER: ${{ secrets.DEMO_BEARER }}
        run: |
          sed -i -e "s/bearer=.*/bearer=$DEMO_BEARER/" ./src/test/resources/demo_env.properties
          cat ./src/test/resources/demo_env.properties
        
      - name: Cucumber tests with Maven on demo platform
        id: demo_supervision
        run: mvn --batch-mode test -Dcucumber.filter.tags=@tagSupervision -Dusing_platform=demo
        continue-on-error: true      
        
      - name: Failure action slack-send
        if: steps.demo_supervision.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.21.0
        with:
          # Slack channel ID where message will be posted. Needed if using bot token
          channel-id: C01UWHG2FGU
          # Message to post into Slack. Needed if using bot token
          slack-message: Demo supervision failure

        
