# This is a basic workflow to help you get started with Actions

name: Supervision

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Checkout sources
        uses: actions/checkout@v1
        with:
          ref: refs/heads/add_cucumber_based_supervision

      - name: Compile with Maven, with no test
        run: mvn --batch-mode -P jacoco compile
        
      - name: Cucumber tests with Maven
        run: mvn --batch-mode test -Dcucumber.filter.tags=@tagSupervision -Dusing_platform=demo
